# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 9cf97d4
_src_path: gh:scipp/copier_template
description: Validate NeXus files
max_python: '3.12'
min_python: '3.10'
namespace_package: ''
nightly_deps: ''
orgname: scipp
projectname: notevennexus
related_projects: ScippNexus
year: 2023
